### 쿠폰 발급
POST http://localhost:8080/api/v1/coupon/generate
content-type: application/json

{
  "couponName" : "EST 직원 30%할인 쿠폰",
  "couponType": "PERCENTAGE",
  "couponEventType": "EVENT",
  "quantity": 100
}

### 쿠폰 사용
@memberId = 1
POST http://localhost:8080/api/v1/coupon/issued/{{memberId}}
content-type: application/json

{
  "couponId" : 1
}
